In [4]:
import pandas as pd
df = pd.read_csv('/content/Advanced_pandas_sales_dataset.csv')

In [5]:
df

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
...,...,...,...,...,...,...,...,...,...,...,...
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
226,1227,2024-04-02,Dev,Pune,South,Mouse,Accessories,1669,6,0.05,323.13
227,1228,2024-01-14,Vikas,Chennai,North,Tablet,Electronics,2682,7,0.15,119.82
228,1229,2024-09-04,Priya,Pune,East,Tablet,Electronics,2635,8,0.00,531.76
229,1230,2024-04-13,Meera,Kolkata,North,Monitor,Electronics,5087,8,0.10,416.72

# Q1 Dataset Exploration

Perform the following exploratory steps:

Display the first 10 rows

Display the dataset structure using info()

Find the number of rows and columns

Identify the data types of each column

In [8]:
# First_10_Rows
df.head(10)

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
5,1006,2024-07-04,Pooja,Bangalore,West,Printer,Office,3073,8,0.20,191.58
6,1007,2024-06-24,Dev,Chennai,East,Monitor,Electronics,1170,5,0.20,22.83
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
9,1010,2024-12-25,Pooja,Ahmedabad,North,Phone,Electronics,2711,8,0.00,477.32

In [9]:
#Database_Structure using info()

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    230 non-null    int64
 1   Order_Date  230 non-null    object
 2   Customer    230 non-null    object
 3   City        230 non-null    object
 4   Region      230 non-null    object
 5   Product     230 non-null    object
 6   Category    230 non-null    object
 7   Sales       230 non-null    int64
 8   Quantity    230 non-null    int64
 9   Discount    230 non-null    float64
 10  Profit      230 non-null    float64
dtypes: float64(2), int64(3), object(6)
memory usage: 19.9+ KB

In [10]:
# Find_the_Number_of_Rows & Columns

df.shape

(230, 11)

In [15]:
#Identify the data types of each column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    230 non-null    int64
 1   Order_Date  230 non-null    object
 2   Customer    230 non-null    object
 3   City        230 non-null    object
 4   Region      230 non-null    object
 5   Product     230 non-null    object
 6   Category    230 non-null    object
 7   Sales       230 non-null    int64
 8   Quantity    230 non-null    int64
 9   Discount    230 non-null    float64
 10  Profit      230 non-null    float64
dtypes: float64(2), int64(3), object(6)
memory usage: 19.9+ KB

Q2 Sales Filtering Analysis

Filter the dataset to display:

1. Orders where Sales > 3500

2. Orders where Region = "East" and Sales > 2500

Explain what insights you observe.

In [16]:
#1. Find where Sales > 3500

df[df['Sales']>=3500]

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
10,1011,2024-06-30,Neha,Delhi,South,Printer,Office,5977,6,0.00,1578.32
...,...,...,...,...,...,...,...,...,...,...,...
219,1220,2024-03-22,Meera,Bangalore,West,Phone,Electronics,5986,7,0.05,986.70
222,1223,2024-03-04,Meera,Ahmedabad,South,Phone,Electronics,4356,6,0.10,416.87
223,1224,2024-01-07,Dev,Bangalore,East,Tablet,Electronics,4115,4,0.05,870.03
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
229,1230,2024-04-13,Meera,Kolkata,North,Monitor,Electronics,5087,8,0.10,416.72

In [17]:
#Find where Region = "East" and Sales > 2500

df[(df['Region']=="East") & (df["Sales"]>=2500)]

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
13,1014,2024-03-18,Anita,Bangalore,East,Mouse,Accessories,3616,4,0.05,463.93
21,1022,2024-01-14,Nitin,Chennai,East,Monitor,Electronics,4827,6,0.05,912.34
27,1028,2024-07-21,Dev,Kolkata,East,Tablet,Electronics,4054,6,0.00,1013.83
33,1034,2024-12-15,Nitin,Ahmedabad,East,Tablet,Electronics,4378,2,0.20,-104.30
34,1035,2024-02-20,Nitin,Ahmedabad,East,Laptop,Electronics,2535,4,0.10,188.15
41,1042,2024-07-15,Rohan,Chennai,East,Laptop,Electronics,3268,8,0.15,295.15
43,1044,2024-09-20,Kavya,Hyderabad,East,Printer,Office,2618,7,0.05,454.64
52,1053,2024-05-24,Anita,Chennai,East,Phone,Electronics,5949,7,0.20,220.44
55,1056,2024-01-03,Sneha,Chennai,East,Headphones,Accessories,2784,4,0.05,474.60
58,1059,2024-12-30,Anita,Delhi,East,Tablet,Electronics,4790,1,0.20,238.53
60,1061,2024-02-05,Nitin,Delhi,East,Monitor,Electronics,4508,5,0.00,972.35
70,1071,2024-05-28,Vikas,Hyderabad,East,Mouse,Accessories,3762,2,0.05,719.68
71,1072,2024-05-20,Rahul,Chennai,East,Printer,Office,3696,2,0.10,600.75
73,1074,2024-10-10,Sara,Bangalore,East,Mouse,Accessories,4004,1,0.15,445.81
74,1075,2024-11-25,Pooja,Ahmedabad,East,Laptop,Electronics,3865,8,0.20,174.96
76,1077,2024-03-02,Neha,Pune,East,Monitor,Electronics,2964,8,0.20,109.33
81,1082,2024-08-16,Isha,Chennai,East,Phone,Electronics,2720,4,0.15,163.13
87,1088,2024-07-29,Pooja,Mumbai,East,Headphones,Accessories,4811,4,0.20,-25.47
92,1093,2024-01-13,Karan,Kolkata,East,Laptop,Electronics,5372,3,0.15,136.64
96,1097,2024-06-07,Isha,Delhi,East,Phone,Electronics,5096,4,0.15,283.66
98,1099,2024-07-26,Rahul,Kolkata,East,Laptop,Electronics,5674,7,0.05,1141.51
108,1109,2024-10-23,Raj,Hyderabad,East,Tablet,Electronics,2509,4,0.05,371.67
109,1110,2024-11-28,Priya,Ahmedabad,East,Printer,Office,2561,4,0.20,57.96
112,1113,2024-11-01,Meera,Bangalore,East,Tablet,Electronics,4179,5,0.00,754.64
113,1114,2024-05-10,Rahul,Bangalore,East,Mouse,Accessories,3285,3,0.00,625.46
116,1117,2024-12-07,Pooja,Kolkata,East,Tablet,Electronics,3758,5,0.15,446.54
128,1129,2024-06-09,Nitin,Delhi,East,Laptop,Electronics,5713,3,0.00,1498.02
139,1140,2024-05-04,Karan,Ahmedabad,East,Monitor,Electronics,3500,8,0.05,467.16
141,1142,2024-01-01,Rahul,Mumbai,East,Headphones,Accessories,5430,8,0.05,741.25
146,1147,2024-05-31,Raj,Delhi,East,Keyboard,Accessories,5709,7,0.20,383.58
152,1153,2024-02-27,Rahul,Mumbai,East,Phone,Electronics,3644,2,0.05,512.25
156,1157,2024-05-27,Neha,Kolkata,East,Laptop,Electronics,4906,4,0.00,1115.89
171,1172,2024-09-22,Neha,Hyderabad,East,Headphones,Accessories,4228,1,0.20,236.15
179,1180,2024-12-13,Neha,Ahmedabad,East,Monitor,Electronics,2690,7,0.10,452.70
182,1183,2024-12-01,Pooja,Chennai,East,Laptop,Electronics,5884,1,0.05,1266.10
185,1186,2024-03-12,Kavya,Ahmedabad,East,Phone,Electronics,5047,2,0.10,564.78
187,1188,2024-07-10,Isha,Kolkata,East,Mouse,Accessories,4333,8,0.10,667.53
193,1194,2024-07-23,Pooja,Delhi,East,Laptop,Electronics,3767,7,0.20,103.23
197,1198,2024-10-16,Rahul,Ahmedabad,East,Tablet,Electronics,3955,1,0.10,284.92
202,1203,2024-05-10,Rahul,Mumbai,East,Phone,Electronics,2901,8,0.15,252.25
207,1208,2024-04-29,Dev,Chennai,East,Monitor,Electronics,3585,7,0.15,287.44
216,1217,2024-08-16,Karan,Chennai,East,Monitor,Electronics,2643,5,0.15,78.53
223,1224,2024-01-07,Dev,Bangalore,East,Tablet,Electronics,4115,4,0.05,870.03
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
228,1229,2024-09-04,Priya,Pune,East,Tablet,Electronics,2635,8,0.00,531.76

# Q3 Customer Purchase Analysis

Identify the top 5 customers based on total sales.

Hint: Use GroupBy with aggregation.

In [24]:
#tpo 5 customer sbased o total Sales.

df['Total_sales'] = df['Sales'] * df['Quantity']
print(df)

df1 = df.groupby('Customer')['Total_sales'].sum().nlargest(5)
print('Top 5 Customers', df1)

     Order_ID  Order_Date Customer       City Region   Product     Category  \
0        1001  2024-10-01    Priya  Hyderabad   East     Mouse  Accessories
1        1002  2024-05-03    Sneha    Kolkata   East   Monitor  Electronics
2        1003  2024-01-26    Anita     Mumbai   West     Phone  Electronics
3        1004  2024-06-06     Sara       Pune   East  Keyboard  Accessories
4        1005  2024-10-15    Rahul  Bangalore  South   Monitor  Electronics
..        ...         ...      ...        ...    ...       ...          ...
225      1226  2024-06-14    Anita  Ahmedabad   East    Laptop  Electronics
226      1227  2024-04-02      Dev       Pune  South     Mouse  Accessories
227      1228  2024-01-14    Vikas    Chennai  North    Tablet  Electronics
228      1229  2024-09-04    Priya       Pune   East    Tablet  Electronics
229      1230  2024-04-13    Meera    Kolkata  North   Monitor  Electronics

     Sales  Quantity  Discount  Profit  Total_sales
0     1735         7      0.00  307.52        12145
1      807         2      0.15   49.89         1614
2     2328         1      0.20   66.47         2328
3     3933         3      0.20  -71.66        11799
4     3550         2      0.20  146.30         7100
..     ...       ...       ...     ...          ...
225   5647         2      0.15  662.00        11294
226   1669         6      0.05  323.13        10014
227   2682         7      0.15  119.82        18774
228   2635         8      0.00  531.76        21080
229   5087         8      0.10  416.72        40696

[230 rows x 12 columns]
Top 5 Customers Customer
Nitin    315917
Raj      259010
Dev      243084
Pooja    233715
Isha     233161
Name: Total_sales, dtype: int64

# Q4 Regional Sales Performance

Calculate the total sales generated by each region.

Then identify:

Which region generated the highest revenue?

In [30]:
#Total_Sales generated by each region.
Sales_by_region = df.groupby('Region')['Total_sales'].sum()
print(Sales_by_region)

Region
East     1066163
North     692358
South     888723
West      813486
Name: Total_sales, dtype: int64

In [34]:
# Find the region with the highest revenue
highest_region = Sales_by_region.idxmax()
highest_revenue = Sales_by_region.max()

print("Region with highest revenue:", highest_region)
print("Highest revenue:", highest_revenue)

Region with highest revenue: East
Highest revenue: 1066163

# Q5 Product Performance Analysis

Calculate the total quantity sold for each product.

Which product appears to be the most popular?

In [37]:
#The Total Quantity for each Product.
Quantity_of_each_products = df.groupby('Product')['Quantity'].sum()
print(Quantity_of_each_products)

Product
Headphones    115
Keyboard      110
Laptop        140
Monitor       156
Mouse         122
Phone         151
Printer       108
Tablet        150
Name: Quantity, dtype: int64

In [38]:
#Most popular product
most_popular_products = Quantity_of_each_products.idxmax()
print(most_popular_products)

Monitor

# Q6 Multi-Level Grouping

Group the dataset by: Region and Categor

Calculate the total sales for each combination.

What insights can you derive from this analysis?

In [43]:
#Group dataset by region and categor

Region_categor = df.groupby('Region')['Category'].value_counts()
print(Region_categor)

Region  Category
East    Electronics    48
        Accessories    18
        Office          6
North   Electronics    23
        Accessories    22
        Office          8
South   Electronics    26
        Accessories    24
        Office          4
West    Electronics    26
        Accessories    17
        Office          8
Name: count, dtype: int64

In [44]:
#Calculate the total sales for each combination.

Total_sales_for_each_combination = df.groupby(['Region', 'Category'])['Total_sales'].sum()
print(Total_sales_for_each_combination)

Region  Category
East    Accessories    256458
        Electronics    750843
        Office          58862
North   Accessories    227592
        Electronics    352663
        Office         112103
South   Accessories    382398
        Electronics    432383
        Office          73942
West    Accessories    297084
        Electronics    428248
        Office          88154
Name: Total_sales, dtype: int64

1. In this insight . we get East Region is higher demand of electronic products

2.South is good market for electronic Accesssories

3.

# Q7 Pivot Table Creation

Create a pivot table showing:

Rows → Region

Columns → Product

Values → Total Sales

Which region sells the most laptops?

In [46]:
from numpy._core.defchararray import index
pivot = pd.pivot_table(df, values='Total_sales', index='Region', columns='Product', aggfunc='sum')
print(pivot)

Product  Headphones  Keyboard  Laptop  Monitor   Mouse   Phone  Printer  \
Region
East         101095     55371  242366   195765   99992  183626    58862
North         45503     78244   27240    73462  103845  158584   112103
South        111655    119912  115165    99232  150831   99407    73942
West          69067    180683   62629   115536   47334  134027    88154

Product  Tablet
Region
East     129086
North     93377
South    118579
West     116056

In [47]:
Sell_most_laptops = pivot.idxmax()  #Which region sells the most laptops?
print(Sell_most_laptops)

Product
Headphones    South
Keyboard       West
Laptop         East
Monitor        East
Mouse         South
Phone          East
Printer       North
Tablet         East
dtype: object

# Q8 Profitability Analysis

Calculate the average profit for each product category.

Which category is most profitable?

In [48]:
from numpy import average
#Profit for each product category.
average_profit_each_category = df.groupby('Category')['Profit'].mean()
print(average_profit_each_category)

Category
Accessories    410.603086
Electronics    396.462114
Office         471.938462
Name: Profit, dtype: float64

In [49]:
#Which category is most profitable?
profitable_category = average_profit_each_category.idxmax()
print(profitable_category)

Office

# Q9 Discount Impact Study

Analyze the relationship between discount and profit.

Tasks:

Calculate the average profit for each discount level

Identify whether higher discounts lead to lower profit

In [50]:
dis_relation = df.groupby('Discount')['Profit'].mean()
print(dis_relation)

Discount
0.00    751.210588
0.05    531.368039
0.10    346.460513
0.15    237.191400
0.20     90.026923
Name: Profit, dtype: float64

In [51]:
#calculate the average profit for each discount level
average_profit_for_each_discount = df.groupby('Discount')['Profit'].mean()
print(average_profit_for_each_discount)
#

Discount
0.00    751.210588
0.05    531.368039
0.10    346.460513
0.15    237.191400
0.20     90.026923
Name: Profit, dtype: float64

In [52]:
# Identify whether higher discounts lead to lower profit
higher_dis_lower_profit = dis_relation.idxmin()
print(higher_dis_lower_profit)

0.2

# Q10 End-to-End Data Wrangling Task

Perform the following workflow:

1. Filter the dataset where Sales > 3000

2. Group data by Region and Product

3. Calculate total sales

4. Reshape the result into a pivot table

Explain the business insights obtained from this analysis.

In [53]:
#Filter the dataset where Sales > 3000

df1 = df[df['Sales'] > 3000]
print(df1)

     Order_ID  Order_Date Customer       City Region   Product     Category  \
3        1004  2024-06-06     Sara       Pune   East  Keyboard  Accessories
4        1005  2024-10-15    Rahul  Bangalore  South   Monitor  Electronics
5        1006  2024-07-04    Pooja  Bangalore   West   Printer       Office
7        1008  2024-03-18    Kavya    Kolkata   East     Phone  Electronics
8        1009  2024-10-31    Kavya  Ahmedabad   East     Phone  Electronics
..        ...         ...      ...        ...    ...       ...          ...
219      1220  2024-03-22    Meera  Bangalore   West     Phone  Electronics
222      1223  2024-03-04    Meera  Ahmedabad  South     Phone  Electronics
223      1224  2024-01-07      Dev  Bangalore   East    Tablet  Electronics
225      1226  2024-06-14    Anita  Ahmedabad   East    Laptop  Electronics
229      1230  2024-04-13    Meera    Kolkata  North   Monitor  Electronics

     Sales  Quantity  Discount  Profit  Total_sales
3     3933         3      0.20  -71.66        11799
4     3550         2      0.20  146.30         7100
5     3073         8      0.20  191.58        24584
7     4693         7      0.05  918.49        32851
8     5071         6      0.10  707.55        30426
..     ...       ...       ...     ...          ...
219   5986         7      0.05  986.70        41902
222   4356         6      0.10  416.87        26136
223   4115         4      0.05  870.03        16460
225   5647         2      0.15  662.00        11294
229   5087         8      0.10  416.72        40696

[115 rows x 12 columns]

In [54]:
#Group data by Region and Product

df2 = df1.groupby(['Region', 'Product'])
print(df2)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x78773658c1b0>